version: '3.9'

services:
  hospital_lc:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/lc_logs
    
    container_name: lc_hospital
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=lintcloud
      - POSTGRES_DB=jarvis_1


